-- Oracle Schema Generation Script for BUSTICKET
-- Generated based on prisma.schema
-- Database Version: Oracle 23ai (Compatible with 19c+)

-- =======================================================
-- 1. CLEANUP (Optional - Uncomment to drop existing tables)
-- =======================================================
/*
DROP TABLE "TicketPayment" CASCADE CONSTRAINTS;
DROP TABLE "payment_history" CASCADE CONSTRAINTS;
DROP TABLE "Ticket" CASCADE CONSTRAINTS;
DROP TABLE "DropoffPoint" CASCADE CONSTRAINTS;
DROP TABLE "Schedule" CASCADE CONSTRAINTS;
DROP TABLE "Route" CASCADE CONSTRAINTS;
DROP TABLE "Seat" CASCADE CONSTRAINTS;
DROP TABLE "Bus" CASCADE CONSTRAINTS;
DROP TABLE "Brand" CASCADE CONSTRAINTS;
DROP TABLE "User" CASCADE CONSTRAINTS;
DROP TABLE "Role" CASCADE CONSTRAINTS;
DROP TABLE "Review" CASCADE CONSTRAINTS;
DROP TABLE "Notification" CASCADE CONSTRAINTS;
DROP TABLE "Promotion" CASCADE CONSTRAINTS;
*/

-- =======================================================
-- 2. TABLES & SEQUENCES
-- =======================================================

-- Table: Role
CREATE TABLE "Role" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "name" VARCHAR2(50) NOT NULL UNIQUE,
    CHECK ("name" IN ('ADMIN', 'PASSENGER'))
);

-- Table: User
CREATE TABLE "User" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "uid" VARCHAR2(255) NOT NULL UNIQUE,
    "name" VARCHAR2(255) NOT NULL,
    "email" VARCHAR2(255) NOT NULL UNIQUE,
    "phone" VARCHAR2(50),
    "dob" DATE DEFAULT TO_DATE('1970-01-01', 'YYYY-MM-DD'),
    "gender" VARCHAR2(20) DEFAULT 'OTHER',
    "avatar" VARCHAR2(1000),
    "faceUrl" VARCHAR2(1000),
    "isActive" NUMBER(1) DEFAULT 1 NOT NULL CHECK ("isActive" IN (0, 1)),
    "roleId" NUMBER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_user_role" FOREIGN KEY ("roleId") REFERENCES "Role"("id")
);

-- Table: Brand
CREATE TABLE "Brand" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL UNIQUE,
    "phoneNumber" VARCHAR2(50),
    "image" VARCHAR2(1000),
    "address" VARCHAR2(1000),
    "dailyTicketLimit" NUMBER DEFAULT 100 NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Table: Bus
CREATE TABLE "Bus" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "name" VARCHAR2(255) NOT NULL,
    "licensePlate" VARCHAR2(50) NOT NULL UNIQUE,
    "seatCount" NUMBER NOT NULL,
    "category" VARCHAR2(50) NOT NULL,
    "seatType" VARCHAR2(50) NOT NULL,
    "berthType" VARCHAR2(50),
    "brandId" NUMBER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_bus_brand" FOREIGN KEY ("brandId") REFERENCES "Brand"("id"),
    CHECK ("category" IN ('MINIVAN', 'COACH', 'LIMOUSINE', 'SLEEPER', 'VIP')),
    CHECK ("seatType" IN ('SEAT', 'BERTH')),
    CHECK ("berthType" IN ('SINGLE', 'DOUBLE'))
);

-- Table: Seat
CREATE TABLE "Seat" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "seatNumber" NUMBER NOT NULL,
    "code" VARCHAR2(50) NOT NULL, 
    "isAvailable" NUMBER(1) DEFAULT 1 NOT NULL CHECK ("isAvailable" IN (0, 1)),
    "price" NUMBER(10, 2) NOT NULL,
    "floor" NUMBER,
    "roomType" VARCHAR2(50),
    "busId" NUMBER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_seat_bus" FOREIGN KEY ("busId") REFERENCES "Bus"("id"),
    CHECK ("roomType" IN ('SINGLE', 'DOUBLE')),
    CONSTRAINT "uq_seat_code" UNIQUE ("code")
);

-- Table: Route
CREATE TABLE "Route" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "startPoint" VARCHAR2(255) NOT NULL,
    "endPoint" VARCHAR2(255) NOT NULL,
    "averageDurationMin" NUMBER NOT NULL,
    "lowestPrice" NUMBER(10, 2) NOT NULL,
    "distanceKm" NUMBER(10, 2),
    "brandId" NUMBER,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_route_brand" FOREIGN KEY ("brandId") REFERENCES "Brand"("id")
);

-- Table: Schedule
CREATE TABLE "Schedule" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "busId" NUMBER NOT NULL,
    "routeId" NUMBER NOT NULL,
    "departureAt" TIMESTAMP NOT NULL,
    "arrivalAt" TIMESTAMP NOT NULL,
    "status" VARCHAR2(50) DEFAULT 'UPCOMING' NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_schedule_bus" FOREIGN KEY ("busId") REFERENCES "Bus"("id"),
    CONSTRAINT "fk_schedule_route" FOREIGN KEY ("routeId") REFERENCES "Route"("id"),
    CHECK ("status" IN ('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED', 'FULL', 'FEW_SEATS'))
);

-- Table: DropoffPoint
CREATE TABLE "DropoffPoint" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "scheduleId" NUMBER NOT NULL,
    "name" VARCHAR2(255) NOT NULL,
    "address" VARCHAR2(1000),
    "surcharge" NUMBER(10, 2) DEFAULT 0 NOT NULL,
    "priceDifference" NUMBER(10, 2) DEFAULT 0 NOT NULL,
    "isDefault" NUMBER(1) DEFAULT 0 NOT NULL CHECK ("isDefault" IN (0, 1)),
    "order_num" NUMBER DEFAULT 0 NOT NULL, -- "order" is keyword
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_dropoff_schedule" FOREIGN KEY ("scheduleId") REFERENCES "Schedule"("id")
);

-- Table: PaymentHistory (Mapped from 'payment_history')
CREATE TABLE "payment_history" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "method" VARCHAR2(50) NOT NULL,
    "amount" NUMBER(10, 2) NOT NULL,
    "transactionId" VARCHAR2(255),
    "status" VARCHAR2(50) DEFAULT 'PENDING' NOT NULL,
    "qrCode" CLOB,
    "ticketCode" VARCHAR2(255),
    "seatList" CLOB,
    "seatCount" NUMBER DEFAULT 0 NOT NULL,
    "payUrl" CLOB,
    "paidAt" TIMESTAMP,
    "promotionId" NUMBER,
    "discountAmount" NUMBER(10, 2),
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHECK ("method" IN ('CASH', 'CREDIT_CARD', 'MOMO', 'ZALOPAY', 'VNPAY'))
);

-- Table: Ticket
CREATE TABLE "Ticket" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "userId" NUMBER NOT NULL,
    "scheduleId" NUMBER NOT NULL,
    "seatId" NUMBER NOT NULL,
    "price" NUMBER(10, 2) NOT NULL,
    "surcharge" NUMBER(10, 2) DEFAULT 0 NOT NULL,
    "totalPrice" NUMBER(10, 2) DEFAULT 0 NOT NULL,
    "status" VARCHAR2(50) DEFAULT 'BOOKED' NOT NULL,
    "paymentMethod" VARCHAR2(50),
    "dropoffPointId" NUMBER,
    "dropoffAddress" VARCHAR2(1000),
    "paymentHistoryId" NUMBER,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_ticket_user" FOREIGN KEY ("userId") REFERENCES "User"("id"),
    CONSTRAINT "fk_ticket_schedule" FOREIGN KEY ("scheduleId") REFERENCES "Schedule"("id"),
    CONSTRAINT "fk_ticket_seat" FOREIGN KEY ("seatId") REFERENCES "Seat"("id"),
    CONSTRAINT "fk_ticket_dropoff" FOREIGN KEY ("dropoffPointId") REFERENCES "DropoffPoint"("id"),
    CONSTRAINT "fk_ticket_payment_hist" FOREIGN KEY ("paymentHistoryId") REFERENCES "payment_history"("id"),
    CHECK ("status" IN ('BOOKED', 'PAID', 'CANCELLED')),
    CHECK ("paymentMethod" IN ('CASH', 'CREDIT_CARD', 'MOMO', 'ZALOPAY', 'VNPAY'))
);

-- Table: TicketPayment (Join Table)
CREATE TABLE "TicketPayment" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "ticketId" NUMBER NOT NULL,
    "paymentId" NUMBER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_tp_ticket" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id"),
    CONSTRAINT "fk_tp_payment" FOREIGN KEY ("paymentId") REFERENCES "payment_history"("id"),
    CONSTRAINT "uq_tp_pair" UNIQUE ("ticketId", "paymentId")
);

-- Table: Review
-- Note: 'images' String[] in Prisma.
-- Recommended: Create a separate table "ReviewImages".
-- Option 2 (Simpler): Store as JSON String in a CLOB column.
-- Here we use CLOB with JSON Check for simplicity matching current architecture.
CREATE TABLE "Review" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "rating" NUMBER NOT NULL,
    "comment" CLOB,
    "images" CLOB, -- Stored as JSON Array e.g. '["url1", "url2"]'
    "reply" CLOB,
    "repliedAt" TIMESTAMP,
    "userId" NUMBER NOT NULL,
    "busId" NUMBER NOT NULL,
    "ticketId" NUMBER NOT NULL UNIQUE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_review_user" FOREIGN KEY ("userId") REFERENCES "User"("id"),
    CONSTRAINT "fk_review_bus" FOREIGN KEY ("busId") REFERENCES "Bus"("id"),
    CONSTRAINT "fk_review_ticket" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id"),
    CONSTRAINT "chk_review_images_json" CHECK ("images" IS JSON)
);

-- Table: Promotion
CREATE TABLE "Promotion" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "code" VARCHAR2(50) NOT NULL UNIQUE,
    "description" VARCHAR2(1000) NOT NULL,
    "discountType" VARCHAR2(50) NOT NULL,
    "discountValue" NUMBER(10, 2) NOT NULL,
    "minOrderValue" NUMBER(10, 2) DEFAULT 0 NOT NULL,
    "maxDiscount" NUMBER(10, 2),
    "startDate" TIMESTAMP NOT NULL,
    "endDate" TIMESTAMP NOT NULL,
    "usageLimit" NUMBER DEFAULT 0 NOT NULL,
    "usedCount" NUMBER DEFAULT 0 NOT NULL,
    "isActive" NUMBER(1) DEFAULT 1 NOT NULL CHECK ("isActive" IN (0, 1)),
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CHECK ("discountType" IN ('PERCENTAGE', 'FIXED'))
);

-- Table: Notification
CREATE TABLE "Notification" (
    "id" NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    "userId" NUMBER NOT NULL,
    "title" VARCHAR2(255) NOT NULL,
    "message" CLOB NOT NULL,
    "type" VARCHAR2(50) DEFAULT 'SYSTEM' NOT NULL,
    "isRead" NUMBER(1) DEFAULT 0 NOT NULL CHECK ("isRead" IN (0, 1)),
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "fk_notif_user" FOREIGN KEY ("userId") REFERENCES "User"("id")
);

-- =======================================================
-- 3. INDEXES
-- =======================================================
CREATE INDEX "idx_user_roleId" ON "User"("roleId");

CREATE INDEX "idx_bus_brandId" ON "Bus"("brandId");
CREATE INDEX "idx_schedule_dates" ON "Schedule"("departureAt");
CREATE INDEX "idx_ticket_user" ON "Ticket"("userId");
CREATE INDEX "idx_ticket_status" ON "Ticket"("status");


-- End of Script
